/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "dkxbqfrbelvcjdjsucmh"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRreGJxZnJiZWx2Y2pkanN1Y21oIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzAxOTUyMzMsImV4cCI6MjA4NTc3MTIzM30.AXLa25tTr-PSz4AqBX3-dpHT8EzTtBNvxSspDAWl1ns"